/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import MODEL.AccountDAO;
import MODEL.AccountSG;
import VIEWMODEL.AccountViewModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Allysa Marie Datahan
 */
public class AddUpdateDeanFaculty extends javax.swing.JFrame {
    private final AccountViewModel viewModel = new AccountViewModel();
    
    private char mode;
    private int ID;
    /**
     * Creates new form AddDeanFaculty
     */
    public AddUpdateDeanFaculty(){
        this('O', 0);
    }
    public AddUpdateDeanFaculty(char mode, int ID) {
        this.mode = mode;
        this.ID = ID;
        initComponents();
        
        if(Character.toUpperCase(mode) == 'A'){
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddDeanFacultyBackground.png")));
            ADFAddButton.setText("ADD");
        }else{
            loadAccountDataById(ID);
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UpdateAccBG.png")));
            ADFAddButton.setText("UPDATE");
        }
    }
    
    private void loadAccountDataById(int id) {
        AccountSG.Account account = viewModel.getAccountById(id);

        AccountType.setSelectedItem(account.getAccountType());
        Honorifics.setText(account.getHonorifics());
        AccountName.setText(account.getAccountName());
        RfidNumber.setText(account.getRfid());
        Title.setText(account.getTitle());
        Username.setText(account.getUsername());
        Password.setText(account.getPassword()); // Note: This sets plain text for demo; consider masking/hashing in real use
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AccountType = new javax.swing.JComboBox<>();
        Honorifics = new javax.swing.JTextField();
        AccountName = new javax.swing.JTextField();
        RfidNumber = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        Title = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        ADFShowPassword = new javax.swing.JCheckBox();
        ADFCancelButton = new javax.swing.JButton();
        ADFAddButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccountType.setBackground(new java.awt.Color(255, 255, 255));
        AccountType.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        AccountType.setForeground(new java.awt.Color(0, 0, 0));
        AccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dean", "Faculty" }));
        jPanel1.add(AccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 122, 280, 30));

        Honorifics.setBackground(new java.awt.Color(255, 255, 255));
        Honorifics.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        Honorifics.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Honorifics, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 173, 280, 27));

        AccountName.setBackground(new java.awt.Color(255, 255, 255));
        AccountName.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        AccountName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(AccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 222, 280, 27));

        RfidNumber.setBackground(new java.awt.Color(255, 255, 255));
        RfidNumber.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        RfidNumber.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(RfidNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 320, 280, 27));

        Username.setBackground(new java.awt.Color(255, 255, 255));
        Username.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        Username.setForeground(new java.awt.Color(0, 0, 0));
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 368, 280, 27));

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 270, 280, 27));

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 415, 280, 25));

        ADFShowPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ADFShowPassword.setForeground(new java.awt.Color(0, 0, 0));
        ADFShowPassword.setText("Show Password");
        ADFShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADFShowPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(ADFShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 445, -1, -1));

        ADFCancelButton.setBackground(new java.awt.Color(255, 204, 0));
        ADFCancelButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ADFCancelButton.setForeground(new java.awt.Color(0, 0, 0));
        ADFCancelButton.setText("CANCEL");
        ADFCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADFCancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ADFCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, 30));

        ADFAddButton.setBackground(new java.awt.Color(255, 204, 0));
        ADFAddButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ADFAddButton.setForeground(new java.awt.Color(0, 0, 0));
        ADFAddButton.setText("ADD");
        ADFAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADFAddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ADFAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddDeanFacultyBackground.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ADFCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADFCancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_ADFCancelButtonActionPerformed

    private void ADFAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADFAddButtonActionPerformed
        // Collect input
        String accountType = AccountType.getSelectedItem().toString();
        String honorifics = Honorifics.getText().trim();
        String accountName = AccountName.getText().trim();
        String rfidNumber = RfidNumber.getText().trim();
        String username = Username.getText().trim();
        String title = Title.getText().trim();
        String password = new String(Password.getPassword()).trim();

        // ViewModel instance
        AccountViewModel viewModel = new AccountViewModel();

        // Validate inputs
        String validationMessage = viewModel.getValidationMessage(accountType, honorifics, accountName, username, title, password, rfidNumber);
        if (validationMessage != null) {
            JOptionPane.showMessageDialog(this, validationMessage, "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean success = viewModel.saveAccount(mode, ID, accountType, honorifics, accountName, username, title, password, rfidNumber);

        if (success) {
            String action = (mode == 'A') ? "added" : "updated";
            JOptionPane.showMessageDialog(this, "Account " + action + " successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

            if (mode == 'A') {
                clearForm(); 
            } else {
                dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Failed to " + ((mode == 'A') ? "add" : "update") + " account.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ADFAddButtonActionPerformed

    private void ADFShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADFShowPasswordActionPerformed
        if (ADFShowPassword.isSelected()) {
            Password.setEchoChar((char) 0);
        } else {
            Password.setEchoChar('·');
        }
    }//GEN-LAST:event_ADFShowPasswordActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        Password.setEchoChar('·');
    }//GEN-LAST:event_PasswordActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed
    private void clearForm() {
        AccountType.setSelectedIndex(0);
        Honorifics.setText("");
        AccountName.setText("");
        RfidNumber.setText("");
        Username.setText("");
        Title.setText("");
        Password.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUpdateDeanFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUpdateDeanFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUpdateDeanFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUpdateDeanFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUpdateDeanFaculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADFAddButton;
    private javax.swing.JButton ADFCancelButton;
    private javax.swing.JCheckBox ADFShowPassword;
    private javax.swing.JTextField AccountName;
    private javax.swing.JComboBox<String> AccountType;
    private javax.swing.JTextField Honorifics;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField RfidNumber;
    private javax.swing.JTextField Title;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
