/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import MODEL.SectionDAO;
import MODEL.SectionSG;
import VIEWMODEL.AddUpdateSectionViewModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Allysa Marie Datahan
 */
public class AddUpdateSection extends javax.swing.JFrame {
    private char mode; // "A" for add, "U" for update
    private int sectionID; // only used in update mode
    private AddUpdateSectionViewModel viewModel = new AddUpdateSectionViewModel();

    /**
     * Creates new form AddSection
     */
    public AddUpdateSection(){
        this('O', 0);
    }
    public AddUpdateSection(char mode, int sectionID) {
        this.mode = mode;
        this.sectionID = sectionID;
        initComponents();
        
        if(Character.toUpperCase(mode) == 'A'){
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddSectionBackground.png")));
        }else{
            loadSectionDataById(sectionID);
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UpdateSecBG.png")));
        }
    }
    
    private void loadSectionDataById(int id) {
        SectionSG section = SectionDAO.getSectionById(id);

        if (section != null) {
            Section.setText(section.getSectionName());
            Population.setText(String.valueOf(section.getPopulation()));
        } else {
            JOptionPane.showMessageDialog(this, "Section not found for ID: " + id, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Population = new javax.swing.JTextField();
        Section = new javax.swing.JTextField();
        ASCancelButton = new javax.swing.JButton();
        ASAddButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 360));
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Population.setBackground(new java.awt.Color(255, 255, 255));
        Population.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        Population.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Population, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 260, 40));

        Section.setBackground(new java.awt.Color(255, 255, 255));
        Section.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        Section.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Section, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 260, 40));

        ASCancelButton.setBackground(new java.awt.Color(255, 204, 0));
        ASCancelButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ASCancelButton.setForeground(new java.awt.Color(0, 0, 0));
        ASCancelButton.setText("CANCEL");
        ASCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASCancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ASCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 90, 30));

        ASAddButton.setBackground(new java.awt.Color(255, 204, 0));
        ASAddButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ASAddButton.setForeground(new java.awt.Color(0, 0, 0));
        ASAddButton.setText("ADD");
        ASAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASAddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ASAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddSectionBackground.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ASAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASAddButtonActionPerformed
        dispose();
    }//GEN-LAST:event_ASAddButtonActionPerformed

    private void ASCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASCancelButtonActionPerformed
        String sectionName = Section.getText();
        String population = Population.getText();

        boolean result = viewModel.processSection(mode, sectionID, sectionName, population, this);

        if (result && (Character.toUpperCase(mode) == 'A')) {
            clearForm();// Optional: Clear only on successful add
        }
    }//GEN-LAST:event_ASCancelButtonActionPerformed

    private void clearForm() {
        Section.setText("");
        Population.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUpdateSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUpdateSection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ASAddButton;
    private javax.swing.JButton ASCancelButton;
    private javax.swing.JTextField Population;
    private javax.swing.JTextField Section;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
