/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import static MODEL.SubjectDAO.getSubjectById;
import VIEWMODEL.AddUpdateSubjectViewModel;

import java.util.List;

public class AddUpdateSubject extends javax.swing.JFrame {
    private final AddUpdateSubjectViewModel viewModel = new AddUpdateSubjectViewModel();

    private final String selectedBuilding;
    private final String currentRoomNumber;
    private final String accountName;
    private final char mode; // "ADD" or "UPDATE"
    private int subjectId;

    public AddUpdateSubject() {
        this('O', 0, "", "", "", "");
    }

    public AddUpdateSubject(char mode, int subjectId, String selectedBuilding, String roomNumber, String accountName, String accountType) {
        this.mode = mode;
        this.subjectId = subjectId;
        this.selectedBuilding = selectedBuilding;
        this.currentRoomNumber = roomNumber;
        this.accountName = accountName;

        initComponents();
        this.setLocationRelativeTo(null);
        timePicker1.setEditor(TimeStart);
        timePicker2.setEditor(TimeEnd);

        BuildingNameAndNumber.setText(selectedBuilding + " - " + currentRoomNumber);

        populateSectionComboBox();
        populateTeacherComboBox();

        if (Character.toUpperCase(mode) == 'U') {
            getSubjectById(subjectId);  // Fetch subject details from DB via ViewModel
            viewModel.populateInputs( subjectId, this);
        }
    }
    
    private void populateSectionComboBox() {
        List<String> sections = viewModel.getAllSections();
        SectionName.removeAllItems();
        for (String section : sections) {
            SectionName.addItem(section);
        }
    }

    private void populateTeacherComboBox() {
        List<String> instructors = viewModel.getAllInstructors(accountName);
        Teacher.removeAllItems();
        Teacher.addItem("User");
        for (String instructor : instructors) {
            Teacher.addItem(instructor);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timePicker1 = new raven.datetime.component.time.TimePicker();
        timePicker2 = new raven.datetime.component.time.TimePicker();
        jPanel1 = new javax.swing.JPanel();
        BuildingNameAndNumber = new javax.swing.JLabel();
        ASBackButton = new javax.swing.JButton();
        AUButton = new javax.swing.JButton();
        Subject = new javax.swing.JTextField();
        Schedule = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TimeEnd = new javax.swing.JFormattedTextField();
        TimeStart = new javax.swing.JFormattedTextField();
        Teacher = new javax.swing.JComboBox<>();
        SectionName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(640, 360));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BuildingNameAndNumber.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        BuildingNameAndNumber.setForeground(new java.awt.Color(0, 0, 0));
        BuildingNameAndNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuildingNameAndNumber.setText("BUILDING NAME");
        jPanel1.add(BuildingNameAndNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 640, -1));

        ASBackButton.setBackground(new java.awt.Color(255, 204, 0));
        ASBackButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ASBackButton.setForeground(new java.awt.Color(0, 0, 0));
        ASBackButton.setText("BACK");
        ASBackButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ASBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASBackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ASBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 80, 30));

        AUButton.setBackground(new java.awt.Color(255, 204, 0));
        AUButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AUButton.setForeground(new java.awt.Color(0, 0, 0));
        AUButton.setText("ADD");
        AUButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AUButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AUButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 80, 30));

        Subject.setBackground(new java.awt.Color(255, 255, 255));
        Subject.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        Subject.setForeground(new java.awt.Color(0, 0, 0));
        Subject.setBorder(null);
        jPanel1.add(Subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 152, 267, 25));
        Subject.getAccessibleContext().setAccessibleName("");

        Schedule.setBackground(new java.awt.Color(255, 255, 255));
        Schedule.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        Schedule.setForeground(new java.awt.Color(0, 0, 0));
        Schedule.setBorder(null);
        jPanel1.add(Schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 185, 267, 25));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOTE: (M,T,W,TH, F)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 193, 110, -1));

        TimeEnd.setBackground(new java.awt.Color(255, 255, 255));
        TimeEnd.setForeground(new java.awt.Color(0, 0, 0));
        TimeEnd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TimeEndFocusLost(evt);
            }
        });
        jPanel1.add(TimeEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 115, 270, 30));

        TimeStart.setBackground(new java.awt.Color(255, 255, 255));
        TimeStart.setForeground(new java.awt.Color(0, 0, 0));
        TimeStart.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TimeStartFocusLost(evt);
            }
        });
        TimeStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimeStartMouseClicked(evt);
            }
        });
        jPanel1.add(TimeStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 80, 270, 30));

        Teacher.setBackground(new java.awt.Color(255, 255, 255));
        Teacher.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        Teacher.setForeground(new java.awt.Color(0, 0, 0));
        Teacher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User" }));
        Teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherActionPerformed(evt);
            }
        });
        jPanel1.add(Teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 250, 268, 30));

        SectionName.setBackground(new java.awt.Color(255, 255, 255));
        SectionName.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        SectionName.setForeground(new java.awt.Color(0, 0, 0));
        SectionName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionNameActionPerformed(evt);
            }
        });
        jPanel1.add(SectionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 216, 268, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddSubjectBAckground.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ASBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASBackButtonActionPerformed
        dispose();
    }//GEN-LAST:event_ASBackButtonActionPerformed

    private void AUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AUButtonActionPerformed
        String buildingName = selectedBuilding;
        String roomNumber = currentRoomNumber;
        String timeStart = TimeStart.getText().trim();
        String timeEnd = TimeEnd.getText().trim();
        String subject = Subject.getText().trim().toUpperCase();
        String schedule = Schedule.getText().trim().toUpperCase();
        String section = (String) SectionName.getSelectedItem();
        String teacher = (String) Teacher.getSelectedItem();

        String instructor = teacher.equalsIgnoreCase("User") ? accountName : teacher;

        if (Character.toUpperCase(mode) == 'A') {
            viewModel.addSubject(this, buildingName, roomNumber, timeStart, timeEnd, subject, schedule, instructor, section);
        } else {
            viewModel.updateSubject(this, subjectId, buildingName, roomNumber, timeStart, timeEnd, subject, schedule, instructor, section);
        }
    }
    private void resetFormFields() {
        dispose();
    }//GEN-LAST:event_AUButtonActionPerformed

    private void TimeEndFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TimeEndFocusLost

    }//GEN-LAST:event_TimeEndFocusLost

    private void TimeStartFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TimeStartFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeStartFocusLost

    private void TimeStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimeStartMouseClicked

    }//GEN-LAST:event_TimeStartMouseClicked

    private void SectionNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectionNameActionPerformed

    private void TeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUpdateSubject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ASBackButton;
    private javax.swing.JButton AUButton;
    private javax.swing.JLabel BuildingNameAndNumber;
    public javax.swing.JTextField Schedule;
    public javax.swing.JComboBox<String> SectionName;
    public javax.swing.JTextField Subject;
    public javax.swing.JComboBox<String> Teacher;
    public javax.swing.JFormattedTextField TimeEnd;
    public javax.swing.JFormattedTextField TimeStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private raven.datetime.component.time.TimePicker timePicker1;
    private raven.datetime.component.time.TimePicker timePicker2;
    // End of variables declaration//GEN-END:variables
}
