/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import VIEWMODEL.IpConfigViewModel;

import javax.swing.JOptionPane;
/**
 *
 * @author talai
 */
public class IpConfig extends javax.swing.JFrame {
    
    private final IpConfigViewModel viewModel = new IpConfigViewModel();
    /**
     * Creates new form IpConfig
     */
    public IpConfig() {
        initComponents();
        loadConfigFromViewModel();
    }

        /**
     * Loads configuration from IPCONFIG.txt file and sets text fields.
     */
    private void loadConfigFromViewModel() {
        if (!viewModel.loadConfig()) {
            JOptionPane.showMessageDialog(this, "Config not found!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            IPaddress.setText(viewModel.getIp());
            IPport.setText(viewModel.getPort());
            DBname.setText(viewModel.getDbName());
            DBusername.setText(viewModel.getUsername());
            DBpassword.setText(viewModel.getPassword());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IP = new javax.swing.JLabel();
        DB = new javax.swing.JLabel();
        DBuser = new javax.swing.JLabel();
        DBpass = new javax.swing.JLabel();
        IPaddress = new javax.swing.JTextField();
        DBname = new javax.swing.JTextField();
        DBusername = new javax.swing.JTextField();
        DBpassword = new javax.swing.JPasswordField();
        SaveButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        DBshowpassword = new javax.swing.JCheckBox();
        PortLabel = new javax.swing.JLabel();
        IPport = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IP.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        IP.setLabelFor(IPaddress);
        IP.setText("IP ADDRESS:");
        jPanel1.add(IP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 30));

        DB.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DB.setLabelFor(DBname);
        DB.setText("DATABASE NAME:");
        jPanel1.add(DB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, 30));

        DBuser.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DBuser.setLabelFor(DBusername);
        DBuser.setText("USERNAME:");
        jPanel1.add(DBuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, 30));

        DBpass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DBpass.setLabelFor(DBpassword);
        DBpass.setText("PASSWORD:");
        jPanel1.add(DBpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, 30));
        jPanel1.add(IPaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 380, 30));
        jPanel1.add(DBname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 380, 30));
        jPanel1.add(DBusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 380, 30));

        DBpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(DBpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 380, 30));

        SaveButton.setText("SAVE");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        DBshowpassword.setText("Show Password");
        DBshowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBshowpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(DBshowpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        PortLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PortLabel.setText("PORT:");
        jPanel1.add(PortLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 90, 30));

        IPport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPportActionPerformed(evt);
            }
        });
        jPanel1.add(IPport, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 380, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void DBpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBpasswordActionPerformed
        DBpassword.setEchoChar('·');
    }//GEN-LAST:event_DBpasswordActionPerformed

    private void DBshowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBshowpasswordActionPerformed
        if (DBshowpassword.isSelected()) {
            DBpassword.setEchoChar((char) 0);
        } else {
            DBpassword.setEchoChar('·');
        }
    }//GEN-LAST:event_DBshowpasswordActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        boolean success = viewModel.saveConfig(
        IPaddress.getText(),
        IPport.getText(),
        DBname.getText(),
        DBusername.getText(),
        new String(DBpassword.getPassword())
        );

        if (success) {
            JOptionPane.showMessageDialog(this, "Config saved successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save config.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void IPportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IpConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IpConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IpConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IpConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IpConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel DB;
    private javax.swing.JTextField DBname;
    private javax.swing.JLabel DBpass;
    private javax.swing.JPasswordField DBpassword;
    private javax.swing.JCheckBox DBshowpassword;
    private javax.swing.JLabel DBuser;
    private javax.swing.JTextField DBusername;
    private javax.swing.JLabel IP;
    private javax.swing.JTextField IPaddress;
    private javax.swing.JTextField IPport;
    private javax.swing.JLabel PortLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
