/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import VIEW.IndexView;
import VIEWMODEL.LoginViewModel;

import javax.swing.JOptionPane;
import jd.usbrfiddetector.UsbRfidScanner;
/**
 *
 * @author talai
 */
public class LogIn extends javax.swing.JFrame {
    LoginViewModel viewModel = new LoginViewModel();
    
    private IndexView index;
    
    public LogIn(){
        this(null);
    }
    
    public LogIn(IndexView index) {
        this.index = index;
        initComponents();
        
        rfidField.addActionListener(e -> {
            String scannedRfid = rfidField.getText().trim();
            LoginViewModel.LoginResult result = viewModel.authenticateWithRFID(scannedRfid);

            if (result.success) {
                JOptionPane.showMessageDialog(this, "Welcome " + result.accountName + " (" + result.accountType + ")!");
                // Proceed to appropriate dashboard here...
                openIndex(result);
            } else {
                JOptionPane.showMessageDialog(this, result.message, "RFID Login Failed", JOptionPane.ERROR_MESSAGE);
                rfidField.setText("");
            }
        });
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (index != null) {
                    index.logInInstance = null;
                }
            }
        });
    }
    
    public void openIndex(LoginViewModel.LoginResult result){
        switch (result.accountType) {
            case "Dean":
                JOptionPane.showMessageDialog(this, "Login Successful as Dean!", "Success", JOptionPane.INFORMATION_MESSAGE);
                new IndexView(result.accountName, result.accountType).setVisible(true);
                break;

            case "Faculty":
                JOptionPane.showMessageDialog(this, "Login Successful as Faculty!", "Success", JOptionPane.INFORMATION_MESSAGE);
                new IndexView(result.accountName, result.accountType).setVisible(true);
                break;

            default:
                JOptionPane.showMessageDialog(this, "Invalid AccountType. Please contact the dean's office.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
        }
        dispose();
        index.dispose();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UB = new javax.swing.JLabel();
        CETAFA = new javax.swing.JLabel();
        COMPESA = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        ShowPassword = new javax.swing.JCheckBox();
        ExitButton = new javax.swing.JButton();
        RFIDButton = new javax.swing.JButton();
        BACKGROUND = new javax.swing.JLabel();
        rfidField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N
        UB.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                UBMouseWheelMoved(evt);
            }
        });
        UB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UBMouseClicked(evt);
            }
        });
        jPanel1.add(UB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        CETAFA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        jPanel1.add(CETAFA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        COMPESA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        jPanel1.add(COMPESA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        SubmitButton.setBackground(java.awt.Color.orange);
        SubmitButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(0, 0, 0));
        SubmitButton.setText("SUBMIT");
        SubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 160, 47));

        UsernameField.setBackground(new java.awt.Color(255, 255, 255));
        UsernameField.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 255, 35));

        PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordField.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(0, 0, 0));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 289, 255, 35));

        ShowPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        ShowPassword.setText("Show Password");
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 120, 20));

        ExitButton.setBackground(new java.awt.Color(102, 0, 0));
        ExitButton.setForeground(new java.awt.Color(102, 0, 0));
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/switch.png"))); // NOI18N
        ExitButton.setBorder(null);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        RFIDButton.setBackground(java.awt.Color.orange);
        RFIDButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        RFIDButton.setForeground(new java.awt.Color(0, 0, 0));
        RFIDButton.setText("RFID");
        RFIDButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RFIDButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RFIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFIDButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RFIDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 160, 47));

        BACKGROUND.setBackground(new java.awt.Color(255, 255, 255));
        BACKGROUND.setForeground(new java.awt.Color(255, 255, 255));
        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LogIN.png"))); // NOI18N
        jPanel1.add(BACKGROUND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 570));

        rfidField.setBackground(new java.awt.Color(255, 255, 255));
        rfidField.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        rfidField.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(rfidField, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 255, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String username = UsernameField.getText();
        String password = new String(PasswordField.getPassword());
        
        LoginViewModel.LoginResult result = viewModel.authenticate(username, password);
        if (!result.success) {
            JOptionPane.showMessageDialog(this, result.message, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        openIndex(result);
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        if (ShowPassword.isSelected()) {
            PasswordField.setEchoChar((char) 0);
        } else {
            PasswordField.setEchoChar('·');
        }
    }//GEN-LAST:event_ShowPasswordActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void UBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UBMouseClicked
        //IpConfig next = new IpConfig();
        //next.setVisible(true);
    }//GEN-LAST:event_UBMouseClicked

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        PasswordField.setEchoChar('·');
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void UBMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_UBMouseWheelMoved
        
    }//GEN-LAST:event_UBMouseWheelMoved

    private void RFIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFIDButtonActionPerformed
        boolean rfidConnected = UsbRfidScanner.isRfidScannerConnected();

        if (rfidConnected) {
            JOptionPane.showMessageDialog(this, "RFID scanner detected and ready to scan.", "RFID Detected", JOptionPane.INFORMATION_MESSAGE);
            rfidField.setText("");               // Clear old data
            rfidField.requestFocusInWindow();   // Focus so scanner can type
        } else {
            JOptionPane.showMessageDialog(this, "RFID scanner not detected. Please insert an RFID scanner.", "RFID Not Detected", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_RFIDButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JLabel CETAFA;
    private javax.swing.JLabel COMPESA;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton RFIDButton;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel UB;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField rfidField;
    // End of variables declaration//GEN-END:variables
}
